### PR TITLE
Feature quick map

### PR DESCRIPTION
**Pull request by davidr1234**
Improving map performance by introducing a "limitation" parameter.
Additionally, I added a search for stops. A search for lines maybe an option at some point too.
Line highlighting was introduced, but it's bounding-box-based, so a line-based may be another future improvement.

### CODE REVIEW

**Comment by skinkie** [comment]
I wonder if a true improvement wouldn't be something like an _aggregation_.

**Comment by ue71603** [comment]
> I wonder if a true improvement wouldn't be something like an _aggregation_.

I don't understand your comment.

**Comment by skinkie** [comment]
> > I wonder if a true improvement wouldn't be something like an _aggregation_.
> 
> I don't understand your comment.

I don't see the point of using _less_ routes on a map, than are part of the database. As in the _practical use_.

**Comment by davidr1234** [comment]
The purpose is to simply speed-up the computation time. I am not sure if an aggregation (and its GIS operations) have the same outcome.

**Review by ue71603 — APPROVED** [review]

**Comment by ue71603** [comment]
I think we update it for now and do the next version in #109

**Pull request merged**
