### PR TITLE
Fixing master for different inputs

### PR DESCRIPTION
**Pull request by ue71603**
adaptions needed for Flixbus

### CODE REVIEW

**Comment by ue71603** [comment]
now working on AURA file.

**Comment by ue71603** [comment]
perhaps handling of missing columns could be treated differently...  During import missing columns could be added and filled with default values.

shape_dist_traveled is only optional.

**Comment by ue71603** [comment]
works for AURA now too

**Comment by ue71603** [comment]
SNCF TER processed

**Comment by ue71603** [comment]
https://www.mobidata-bw.de/dataset/soll-fahrplandaten-baden-wurttemberg processed (without shapes)
they forgot the header in trips.txt. 
added it and checked: route_id,service_id,trip_id,trip_short_name,trip_headsign,shape_id,direction_id,block_id,wheelchair_accessible

**Comment by skinkie** [comment]
I don't like it. What I would like to see what I mentioned before. Adding missing columns, not removing things from queries.

**Comment by ue71603** [comment]
So, we can have 
- files missing (already fixed in https://github.com/skinkie/reference/pull/10)
- columns missing
- minimal data entries missing.

**Comment by skinkie** [comment]
I'll implement the full GTFS today.

**Comment by ue71603** [comment]
thanks!

**Comment by skinkie** [comment]
Please check if this one is still relevant.

**Comment by ue71603** [comment]
- import path again yours and not relative in project import.py line 113
- 'UTF-8' is not a valid result for detector.result. It's 'utf-8', 'UTF-8-SIG,' fixed.
- Also I exported the file name as well, which is helpful.
- output encoding not done correctly. must be set to utf-8 (GtfsNeTEx.py 845 & 850)

I create a new PR. Now checking XML output of GTFS2NeTex for the Swiss data. errors found.

**Comment by ue71603** [comment]
one should refresh from ustream first.

**Pull request closed without merging**
