### PR TITLE
better import duckdb

### PR DESCRIPTION
**Pull request by ue71603**

### CODE REVIEW

**Comment by ue71603** [comment]
@skinkie  I did completly not built on your last version. Perhaps we keep this as simpleimport.py

**Comment by skinkie** [comment]
I want to have the column mapping back.

**Comment by ue71603** [comment]
there you are...

**Comment by ue71603** [comment]
@skinkie better

**Comment by skinkie** [comment]
Not my preference.
Create _per file_ a dictionary, having the name, and target SQL type.

**Comment by ue71603** [comment]
you are right. otherwise data types will be very bad.

**Comment by skinkie** [comment]
@ue71603 please evaluate if the current version in master is more than you wanted to do here. I think we can close this one.

**Pull request closed without merging**
