### PR TITLE
Update NeTEx generated classes

### LINKED ISSUE #196: Regenerate NeTEx with latest xsData (fix prohibited objects)

### PR DESCRIPTION
**Pull request by skinkie**
Fix #196

@ue71603 can you check with the regression test if anything in the code breaks?

### CODE REVIEW

**Comment by ue71603** [comment]
Currently problem: 
with nl1
Do I need a new xsdata?
```
Name: xsdata
Version: 24.6.1
Summary: Python XML Binding
Home-page: https://github.com/tefra/xsdata
Author:
Author-email: Christodoulos Tsoulloftas <chris@komposta.net>
License: MIT
Location: C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\.venv\Lib\site-packages
Requires: typing-extensions
Required-by:

```


```

db True
2024-12-16 11:28:14,332 - script_runner - ERROR - No module named 'netex.restricted_service_facility_set_ref': Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\tool_script_runner.py", line 216, in <module>
    main(args.script_file, args.log_file, args.log_level, args.blockname, args.begin_step)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\tool_script_runner.py", line 176, in main
    result=load_and_run(script_name, script_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\tool_script_runner.py", line 28, in load_and_run
    mod = __import__(components[0])
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex_to_db.py", line 3, in <module>
    from netexio.database import Database
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\database.py", line 6, in <module>
    from netexio.pickleserializer import MyPickleSerializer
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\pickleserializer.py", line 1, in <module>
    from netexio.serializer import Serializer
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\serializer.py", line 3, in <module>
    from utils import get_object_name, get_boring_classes, get_interesting_classes
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\utils.py", line 2, in <module>
    import netex
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\__init__.py", line 80, in <module>
    from .access_right_parameter_assignment import AccessRightParameterAssignment
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\access_right_parameter_assignment.py", line 3, in <module>
    from .access_right_parameter_assignment_version_structure import AccessRightParameterAssignmentVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\access_right_parameter_assignment_version_structure.py", line 14, in <module>
    from .dynamic_distance_matrix_element import DynamicDistanceMatrixElement
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\dynamic_distance_matrix_element.py", line 3, in <module>
    from .dynamic_distance_matrix_element_version_structure import DynamicDistanceMatrixElementVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\dynamic_distance_matrix_element_version_structure.py", line 3, in <module>
    from .distance_matrix_element_version_structure import DistanceMatrixElementVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\distance_matrix_element_version_structure.py", line 9, in <module>
    from .geographical_structure_factors_rel_structure import GeographicalStructureFactorsRelStructure
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\geographical_structure_factors_rel_structure.py", line 4, in <module>
    from .geographical_structure_factor import GeographicalStructureFactor
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\geographical_structure_factor.py", line 3, in <module>
    from .geographical_structure_factor_version_structure import GeographicalStructureFactorVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\geographical_structure_factor_version_structure.py", line 9, in <module>
    from .priceable_object_version_structure import FareStructureFactorVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\priceable_object_version_structure.py", line 78, in <module>
    from .fare_table_columns_rel_structure import FareTableColumnsRelStructure
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\fare_table_columns_rel_structure.py", line 8, in <module>
    from .object_refs_rel_structure import ObjectRefsRelStructure
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\object_refs_rel_structure.py", line 337, in <module>
    from .restricted_service_facility_set_ref import RestrictedServiceFacilitySetRef
ModuleNotFoundError: No module named 'netex.restricted_service_facility_set_ref'

2024-12-16 11:28:14,332 - script_runner - ERROR - No module named 'netex.restricted_service_facility_set_ref': Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\tool_script_runner.py", line 216, in <module>
    main(args.script_file, args.log_file, args.log_level, args.blockname, args.begin_step)
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\tool_script_runner.py", line 176, in main
    result=load_and_run(script_name, script_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\tool_script_runner.py", line 28, in load_and_run
    mod = __import__(components[0])
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex_to_db.py", line 3, in <module>
    from netexio.database import Database
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\database.py", line 6, in <module>
    from netexio.pickleserializer import MyPickleSerializer
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\pickleserializer.py", line 1, in <module>
    from netexio.serializer import Serializer
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netexio\serializer.py", line 3, in <module>
    from utils import get_object_name, get_boring_classes, get_interesting_classes
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\utils.py", line 2, in <module>
    import netex
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\__init__.py", line 80, in <module>
    from .access_right_parameter_assignment import AccessRightParameterAssignment
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\access_right_parameter_assignment.py", line 3, in <module>
    from .access_right_parameter_assignment_version_structure import AccessRightParameterAssignmentVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\access_right_parameter_assignment_version_structure.py", line 14, in <module>
    from .dynamic_distance_matrix_element import DynamicDistanceMatrixElement
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\dynamic_distance_matrix_element.py", line 3, in <module>
    from .dynamic_distance_matrix_element_version_structure import DynamicDistanceMatrixElementVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\dynamic_distance_matrix_element_version_structure.py", line 3, in <module>
    from .distance_matrix_element_version_structure import DistanceMatrixElementVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\distance_matrix_element_version_structure.py", line 9, in <module>
    from .geographical_structure_factors_rel_structure import GeographicalStructureFactorsRelStructure
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\geographical_structure_factors_rel_structure.py", line 4, in <module>
    from .geographical_structure_factor import GeographicalStructureFactor
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\geographical_structure_factor.py", line 3, in <module>
    from .geographical_structure_factor_version_structure import GeographicalStructureFactorVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\geographical_structure_factor_version_structure.py", line 9, in <module>
    from .priceable_object_version_structure import FareStructureFactorVersionStructure
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\priceable_object_version_structure.py", line 78, in <module>
    from .fare_table_columns_rel_structure import FareTableColumnsRelStructure
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\fare_table_columns_rel_structure.py", line 8, in <module>
    from .object_refs_rel_structure import ObjectRefsRelStructure
  File "C:\Users\ue71603\MG_Daten\github\reference1\gtfs-netex-test\netex\object_refs_rel_structure.py", line 337, in <module>
    from .restricted_service_facility_set_ref import RestrictedServiceFacilitySetRef
ModuleNotFoundError: No module named 'netex.restricted_service_facility_set_ref'

```

**Comment by skinkie** [comment]
`pip install xsdata[cli,soap,lxml] --upgrade`

**Comment by skinkie** [comment]
Ok, that is something we also must 'automate' with a reusable script.

**Comment by skinkie** [comment]
@ue71603 can you in future always provide the exact commandline for the tool runner?

**Pull request merged**
