### PR TITLE
creating config and fixing non-eisting elements in any-to-epip, when …

### PR DESCRIPTION
**Pull request by ue71603**
…coming from GTFS

* started with a configuration file (as we don't have the same configuration)
* Some elements don't exist when doing import.py GtfsNeTex.py then any-to-EPIP. They are now optional. Perhaps this is not what you want.

Tested it with flixbus:
* https://transport.data.gouv.fr/resources/11681?id=11681&locale=en
and blablacarbus
* https://transport.data.gouv.fr/datasets/blablacar-bus-horaires-theoriques-et-temps-reel-du-reseau-europeen

### CODE REVIEW

**Comment by ue71603** [comment]
need still to test blablacarbus... there seems to be a bug somewhere...

**Comment by skinkie** [comment]
I don't think we will continue with any to epip. I think the process wil be something like anytodb. Then some epip validation magic. And then dbtoepip. For things you would know a priori what you would need in can be optimised.

**Comment by ue71603** [comment]
@skinkie  the pr is out of synch, but we need something like that. Otherwise I always have to patch stuff, before I can make it work. I don't in a linux environment and I don't have  your directory structre. I would really want to steer this from a config file.

**Comment by ue71603** [comment]
data pipelines

**Pull request closed without merging**
