### PR TITLE
fix output encoding

### PR DESCRIPTION
**Pull request by ue71603**

### CODE REVIEW

**Comment by skinkie** [comment]
It should be done differently. Some function where Python implements 'iconv' functionality hence, open in encoding 1 write it to UTF-8. Then DuckDB can naively load it as UTF-8.

**Comment by ue71603** [comment]
My tools don't complain about the input files. They are utf-8. I think somehting within python went wrong. Or open does not use utf-8 by default.

**Comment by ue71603** [comment]
I did the trick from https://stackoverflow.com/questions/36303919/what-encoding-does-open-use-by-default

    print(locale.getpreferredencoding())

on my machine it returned: cp1252

So that's what open was using. I guess you don't hve that on your unix machine. 

This will not end before python 3.15: https://peps.python.org/pep-0686/

**Comment by ue71603** [comment]
meaning: my way is ok :-)

**Comment by skinkie** [comment]
> meaning: my way is ok :-)

Only _then_ we keep it.

**Pull request merged**
